version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: infra/app/Dockerfile
    volumes:
      - ./app:/app
    ports:
        - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

volumes:
  db-volume:
